# Generated by Django 5.0.6 on 2024-07-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.division')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='matches.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='matches.team')),
            ],
        ),
    ]
