# Generated by Django 5.0.6 on 2024-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='place_name',
            field=models.CharField(default='Unknown Place', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='Unknown', upload_to='team_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
