# Generated by Django 5.0.6 on 2024-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_place_name_alter_division_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='place_name',
            field=models.CharField(default='Unknown Place', max_length=255),
        ),
    ]
