# Generated by Django 5.0.6 on 2024-07-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='place_name',
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_place', to='matches.team'),
        ),
    ]
