# Generated by Django 5.0.6 on 2024-07-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_place_name_team_stadium_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_place', to='matches.team'),
        ),
    ]
