# Generated by Django 5.0.6 on 2024-07-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_match_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match_place', to='matches.team'),
            preserve_default=False,
        ),
    ]
